### ISSUE TITLE
last updates

### ISSUE THREAD

**Issue by el3ctron** [datamachine/twx.botapi#13]
when i ask to server:

updates = bot.get_updates().wait()
for update in updates:
    print(update)

sends me all updates and i just want the new ones, there is a way te get this?
thanks

**Comment by Surye** [comment]
http://pythonhosted.org/twx.botapi/twx/botapi/botapi.html#get-updates

You're going to want to keep track of the id of the updates, and send the newest id + 1 as the offset, that will mark all the ones you processed as read, and will no longer return them.

You probably don't want just the newest as there may be more than one update since the last time you got a response. Use this method to only get new updates.

**Comment by el3ctron** [comment]
excelent!! thanks for your help!
